version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: task_admin
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: Task_db
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_admin -d Task_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
